### ISSUE TITLE
theme blog link is not found

### ISSUE THREAD

**Issue by AJLoveChina** [meteorlxy/awesome-vuepress#11]
![image](https://user-images.githubusercontent.com/11222746/58925595-ad9cb900-877a-11e9-9c38-8d858dc71ba7.png)

Hi brother, theme blog link is not found.Could you pls update this?

**Comment by meteorlxy** [comment]
![image](https://user-images.githubusercontent.com/18205362/58933548-324aff80-879a-11e9-9d23-35d39d040688.png)
